<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ApplicationIcon>cl.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="settings.json" />
    <None Remove="cl.png" />
    <EmbeddedResource Include="settings.json" LogicalName="CursorLine.settings.json" />
    <EmbeddedResource Include="cl.png" LogicalName="CursorLine.cl.png" />
  </ItemGroup>

</Project>
